function fig = tester()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load tester

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'PointerShapeCData',mat1, ...
	'Position',[221.25 287.25 420 294.75], ...
   'Tag','Fig1');


% METER
  deg = pi/180;
  angle = [0:2:180]*deg;
  meter_x = cos(angle);
  meter_y = sin(angle);
  meter_axis = nnsfo('a2','Test Output','Widrow-Hoff Meter','');
  set(meter_axis, ...
    'units','points',...
    'position',[225 30 140 70*1.4],...
    'color',nnltyell,...
    'xlim',[-1 1],...
    'ylim',[-0.1 1.3])
  axis('off')
  set(get(gca,'xlabel'),'visible','on')
  fill3([1 meter_x -1],[-0.1 meter_y -0.1],[0 0*meter_x 0]-1,nnltyell,...
    'edgecolor',nndkblue);
  for i=1:91
    line(meter_x(i)*[1 0.95],meter_y(i)*[1 0.95],'color',nndkblue);
  end
  for i=1:15:91
    line(meter_x(i)*[1 0.9],meter_y(i)*[1 0.9],'color',nndkblue);
  end
  for i=-60:30:60
    angle = (90-i)*deg;
    text(cos(angle)*1.2,sin(angle)*1.2,num2str(i),...
      'fontsize',10,...
      'color',nndkblue,...
      'horizontal','center')
  end
  view(2)
  
   % CENTER
  pt = 2/140;
  center = plot(2*pt,-pt,'.',...
    'color',nndkblue,...
    'markersize',16,...
    'erasemode','none');

  % INDICATOR
  angle = (90-a)*deg;
  indicator = line(cos(angle)*[0.07 0.85],sin(angle)*[0.07 0.85],...
    'color',nnred,...
    'linewidth',2,...
    'erasemode','none');

  % BUTTONS
  drawnow;
  if (exist('hintonwb'))
    uicontrol(...
      'units','points',...
      'position',[280 300 60 20],...
      'string','Weights',...
      'callback',[me '(''weight'')'])
end

  uicontrol(...
    'units','points',...
    'position',[410 146 60 20],...
    'string','Train',...
    'callback',[me '(''train'')'])
  uicontrol(...
    'units','points',...
    'position',[410 110 60 20],...
    'string','Contents',...
    'callback','nndtoc')
  uicontrol(...
    'units','points',...
    'position',[410 110-36 60 20],...
    'string','Close',...
    'callback','delete(gcf)')

  % DATA POINTERS
  P_ptr = uicontrol('visible','off'); set(P_ptr,'userdata',P);
  w_ptr = uicontrol('visible','off'); set(w_ptr,'userdata',w);
  b_ptr = uicontrol('visible','off'); set(b_ptr,'userdata',b);
  a_ptr = uicontrol('visible','off'); set(a_ptr,'userdata',a);
  T_ptr = uicontrol('visible','off'); set(T_ptr,'userdata',T);
  p_ptr = uicontrol('visible','off'); set(p_ptr,'userdata',P(:,1));
  
  % SAVE WINDOW DATA AND LOCK
  H = [fig_axis desc_text pattern P_ptr w_ptr select indicator center ...
    b_ptr a_ptr T_ptr error_line p_ptr];
  set(fig,'userdata',H,'nextplot','new','color',nnltgray)

  % INSTRUCTION TEXT
  feval(me,'instr');

  nnchkfs;
